---
title: "R Notebook"
output: html_notebook
---

see https://github.com/chi-feng/mcmc-demo

```{r code9.11}
library(rethinking)
data(rugged)
d <- rugged
d$log_gdp <- log(d$rgdppc_2000)
dd <- d[complete.cases(d$rgdppc_2000),]
dd$log_gdp_std <- dd$log_gdp/mean(dd$log_gdp)
dd$rugged_std<- dd$rugged/max(dd$rugged)
dd$cid <- ifelse(dd$cont_africa==1,1,2)
```

```{r code9.12}
m8.3 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid] + b[cid]*(rugged_std-0.215),
  a[cid] ~ dnorm(1, 0.1),
  b[cid] ~ dnorm(0, 0.3),
  sigma ~ dexp(1)), 
data=dd)

precis(m8.3,depth=2)


```

```{r code9.13}
dat_slim <- list(
  log_gdp_std = dd$log_gdp_std,
  rugged_std = dd$rugged_std,
  cid=as.integer(dd$cid)
)
str(dat_slim)


```


```{r code9.14} 
#modified N cores
m9.1 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid] + b[cid]*(rugged_std-0.215),
  a[cid] ~ dnorm(1, 0.1),
  b[cid] ~ dnorm(0, 0.3),
  sigma ~ dexp(1)), 
data=dat_slim,chains = 2, cores =1)

precis(m9.1)


```